@Conosco_Pizza_.NET_Restful_API_HostAddress = http://localhost:5028

GET {{Conosco_Pizza_.NET_Restful_API_HostAddress}}/pizza/
Accept: application/json

###
GET {{Conosco_Pizza_.NET_Restful_API_HostAddress}}/pizza/1
Accept: application/json

###

POST {{Conosco_Pizza_.NET_Restful_API_HostAddress}}/pizza/
Content-Type: application/json

{
    "name": "Hawaii",
    "isGlutenFree": false
}

###
PUT {{Conosco_Pizza_.NET_Restful_API_HostAddress}}/pizza/3
Content-Type: application/json

{
    "id": 3,
    "name": "Hawaiiiiiaiin",
    "isGlutenFree": false
}

###

DELETE {{Conosco_Pizza_.NET_Restful_API_HostAddress}}/pizza/3

###

